name: ScannerFailure
run-name: ScannerFailure [${{ inputs.customId && inputs.customId || 'N/A' }}]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      customId:
        description: 'run identifier'
        required: false
        default: "No customId set"
  
jobs:
  ScannerFailure:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.customId}}
        run: echo run identifier ${{ inputs.customId }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: SecurityScanner
        uses: schadow98/Schadow-Security-Scanner@main  
        with:
          path: ./failure
          configFile: ./securityScannerConfig.json
          logDir: ./logs_failure
          requirementsFile: ./failure/requirements.txt
  
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecurityScanner
          path: ./logs_failure