name: TestCi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  run-code-scanner:
    uses: schadow98/Schadow-Security-Scanner/.github/workflows/scan.yml@main
