name: ScannerSucess

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ScannerSucess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SecurityScanner
        uses: schadow98/Schadow-Security-Scanner@main  
        with:
          path: ./sucess
          configFile: ./securityScannerConfig.json
          logDir: ./logs_success
          requirementsFile: ./sucess/requirements.txt
        continue-on-error: true
  
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecurityScanner
          path: logs_success